# Generated by Django 5.1.1 on 2024-09-22 12:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('face_encoding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
