# Generated by Django 5.1.1 on 2024-09-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='last_active',
        ),
    ]
