# Generated by Django 5.1.1 on 2024-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='division',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
