# Generated by Django 5.1.1 on 2024-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_division_teacher_teacher_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='division',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='student_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
