# Generated by Django 5.1.1 on 2024-09-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_students_division_students_student_class'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='student',
        ),
    ]
