# Generated by Django 5.1.1 on 2024-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_students_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.ImageField(default=1, upload_to='students/'),
            preserve_default=False,
        ),
    ]
